# Generated by Django 5.2.3 on 2025-07-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(choices=[('music', 'music'), ('drama', 'drama'), ('party', 'party')], on_delete=django.db.models.deletion.CASCADE, to='tasks.category'),
        ),
    ]
