# Generated by Django 5.2.3 on 2025-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_category_name_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('music', 'music'), ('drama', 'drama'), ('party', 'party')], default='drama', max_length=255),
        ),
    ]
